### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#1]
@nipuna777 Could you please add a basic Readme to this repo that has the steps to build/run project?

Doesn't have to be detailed at this point, but should be enough for someone else to get it started.  Thanks!

**Comment by nipuna777** [comment]
So far I've only built and run this project on my development PC.

I will try building and running this on another device and provide  a simple Readme file for the project.

**Comment by nipuna777** [comment]
I've added the readme file and tested the app on a fresh installation in a Virtual Machine. 
It should work but please let me know if something is missing.

**Comment by nipuna777** [comment]
The commit is: https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/2c457c924e6308baf28e4cc88375c83111c86553

**Comment by barbeau** [comment]
Thanks @nipuna777!  I was able to clone, build, and run the project on my machine, so basic Readme looks good for now.  We can refine it later.  So, I'm closing this issue as fixed in https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/2c457c924e6308baf28e4cc88375c83111c86553.
