### ISSUE TITLE
Change the database structure to support storing errors according to the GTFS-RT and GTFS feed

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#10]
The current structure does not support different iterations of the same GTFS feed to be checked. This will be problematic as both the GTFS and GTFS-RT feeds change over time.

**Comment by nipuna777** [comment]
The commit 494e5a1 fixes displaying of errors according to the GTFS feed Iteration. But, more work will have to be done for proper integration once an ORM layer is integrated. 

Moving this to the second milestone.

**Comment by barbeau** [comment]
Closing this as a subset of https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/101.
