### ISSUE TITLE
Show plain text version of feed message when clicking on Log Iteration number

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#100]
**Summary:** 

For each record in the `Log`, we show an `Iteration` number in blue text.  When clicking on this number, it should open up a window showing the plain text version of the protocol buffer that was saved for that iteration (i.e., to view the exact protocol buffer data that generated that particular warning/error in the database).

![image](https://cloud.githubusercontent.com/assets/928045/24570244/7bff1952-1638-11e7-8ae8-7bbe4e633be7.png)

Because we're already storing the binary protocol buffer message for each record in the `Log`, we should just be able to convert this to plain text and show it in a popup window that's scrollable (the text could be quite large).  We should also be able to copy text from the window to the clipboard (e.g., to copy an ID or timestamp from the feed) by clicking and dragging the cursor within the window and using keyboard shortcut (e.g., Ctrl+C), and we should include a "copy-to-clipboard" icon to easily copy the entire protocol buffer text to clipboard (maybe using https://clipboardjs.com/? Or whatever works).  The above mockup has one in the lower-right corner, but I'm open to alternate designs if they make sense.

**Steps to reproduce:** 

Start the validator with feeds

**Expected behavior:** 

Let me click on the `Iteration` number to see the protocol buffer text for the feed iteration that generated that particular error or warning. 

**Observed behavior:** 

Nothing happens when I click on the `Iteration` number.

**Comment by barbeau** [comment]
It looks like https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/src/main/java/edu/usf/cutr/gtfsrtvalidator/helper/ProtoBuf.java has code to convert from `FeedMessage` to JSON plain text.

~~~
 import com.google.transit.realtime.GtfsRealtime;
import com.googlecode.protobuf.format.JsonFormat;

import java.io.FileInputStream;

 public class ProtoBuf {

    //Read profbuf in to JSON
    public static String protoToJSON(String path) {

        String workingDir = System.getProperty("user.dir");
        String tripUpdatePath = workingDir + "/target/classes/tripupdate";
        String json = "";

        try {
            FileInputStream fis = new FileInputStream(tripUpdatePath);
            GtfsRealtime.FeedMessage message = GtfsRealtime.FeedMessage.parseFrom(fis);

            json = JsonFormat.printToString(message);

            //System.out.println(message.toString());
            //json = message.toString();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return json;
    }
}
~~~

We'd already have the `FeedMessage` in memory from reading in the binary from the database.

**Comment by mohangandhiGH** [comment]
Thank you Sean.
