### ISSUE TITLE
Add pagination to Summary and Log tables

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#106]
**Summary:** 

Currently, if we have more than 10 records in the Log for each feed, the last record gets pushed off the bottom of the screen, with no way to retrieve it (see screenshot below where "Iteration 1" has fallen off the screen).

![image](https://cloud.githubusercontent.com/assets/928045/24612747/19ea590c-1854-11e7-8be0-2a6fb16c9419.png)

We should implement pagination for both the Log and Summary so we can access past records easily from the UI.  We need to keep in mind that we could potentially have hundreds/thousands of records, so the pagination implementation needs to scale well both in terms of performance as well as visual representation.

Looks like Bootstrap has some pagination tools:
http://getbootstrap.com/components/#pagination

I'd like to be able to support the following features:

* Step through a set of pages (e.g., if there are a total of 100 pages, let me see 1-10, then 11-20, then 21-30, etc.)
* Change number of records on each page (default of 10 records/page)
* Jump to first/last page
* Jump to specific page (e.g., jump directly to page 51 if it's not visible in the bar)

This demo shows these features:
http://www.pontikis.net/labs/bs_pagination/demo/

"Page 1" should always be the most recent 10 records.

Here's a general mockup of what this should look something like:

![image](https://cloud.githubusercontent.com/assets/928045/24613827/7e8dd656-1857-11e7-8c87-0a44953b2b11.png)

**Steps to reproduce:** 

1. Start the app
1. Let it observe more than 10 iterations of a feed that generates errors or warnings

**Expected behavior:** 

Give me some way to access older records

**Observed behavior:** 

I can't access older records

**Comment by mohangandhiGH** [comment]
@barbeau I started working on this.
