### ISSUE TITLE
Change numbering scheme for errors and warnings

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#12]
The current numbering scheme would not hold up if the number of rules created becomes high. Also, they do not represent the details of the error. (ex e001 only specifies that this is an error. Additional details such as the feeds affected can be shown using this id) 

Changing the numbering scheme before the first milestone would be easier than attempting to do so down the road.

**Comment by barbeau** [comment]
Current numbering scheme seems to work ok, so we'll stick with it for now.
