### ISSUE TITLE
Use ORM tool 

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#14]
Use an ORM tool(Hibernate) for managing the database connectivity While the initial setup was manageable with a direct calls from the JDBC, the validator has grown in complexity which makes it difficult to maintain. In the next major version, Hibernate should be incorporated in order to make thinks easier to maintain

**Comment by barbeau** [comment]
JPA is a good option to look into - http://docs.oracle.com/javaee/6/tutorial/doc/bnbpz.html.
