### ISSUE TITLE
Turning off errors in Log UI can result in hidden records

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#174]
**Summary:** 

If you have a page selected such as 5 of 10, and then hide enough errors in Log UI using the "on/off" switch in Summary section so that page no longer exists (e.g., the number of errors for the remaining visible errors fits onto one page), then the records for that error aren't shown in the Log.

We need to change this behavior so that the remaining page is automatically selected and the user is shown some records for the error that's still turned on in the Summary section.

Here's an example - I've been monitoring this feed for 108 unique iterations, and I've clicked on page 5 in the log:

![image](https://cloud.githubusercontent.com/assets/928045/25532581/d0209ce4-2bfb-11e7-98f9-2dd7764ae309.png)

If I switch off all but E002, this error has only occurred for five iterations, so they all fit on one page.  However, the remaining single page isn't selected by default and therefore no records for this error are shown in the Log:

![image](https://cloud.githubusercontent.com/assets/928045/25532733/532940a0-2bfc-11e7-94dd-da03efdc9f24.png)

If you click on the "Page 1" button in the Log, the records appear:

![image](https://cloud.githubusercontent.com/assets/928045/25532774/7c9b5cd4-2bfc-11e7-8327-a865dadef0d7.png)

**Steps to reproduce:** 

Click on a page number in Log, then then hide enough records using switches in Summary so that page no longer exists.

**Expected behavior:** 

I should immediately see the Log records for the remaining error that I have turned on

**Observed behavior:** 

No records appear in the Log at first, and I have to click on "1" to see them.

**Platform:** 

Windows 7 Enterprise jdk1.8.0_73

**Comment by barbeau** [comment]
Also, the page number is shown incorrectly when the records are hidden - "41-5" in the above screenshot.

**Comment by mohangandhiGH** [comment]
@barbeau Started working on this.
