### ISSUE TITLE
Web app isn't being correctly packaged into JAR

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#181]
**Summary:** 

I noticed this when testing the JAR download from Travis in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/167.

It looks like the web resources aren't being correctly packaged into the JAR file.  If everything was packaged correctly, the JAR should contain all necessary resources to run the application.

However, it seems like the app currently depends on the build folders being available on a fixed path from where the JAR is being executed.  This results in a 404 for the loading page if you try to execute the JAR from the same folder as the JAR:

![image](https://cloud.githubusercontent.com/assets/928045/25560882/9a36f208-2d2d-11e7-9dbc-35b557c55445.png)

We need to fix this so all necessary files are included in the JAR file itself when `mvn package` is executed.

**Steps to reproduce:** 

1. Run `mvn package`
1. Change the directory to the same as the JAR file - `cd target`
1. Run `java -jar target/gtfs-rt-validator-1.0-SNAPSHOT.jar`
1. Enter GTFS and GTFS-rt URLs and click"Start"

**Expected behavior:** 

Run like normal - start validating the feeds and see the monitoring page

**Observed behavior:** 

You see a 404 error.

**Platform:** 

Windows 10 Home with `jdk1.8.0_112`

**Comment by barbeau** [comment]
@mohangandhiGH If you have time, this is the highest priority issue after getting https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/171 ready to merge.

**Comment by mohangandhiGH** [comment]
@barbeau I tried with the steps mentioned in **Steps to Reproduce** section and I'm able to run the application without any errors. 
Am I missing something here to reproduce this issue?

**Comment by barbeau** [comment]
Try copying the JAR to a new directory somewhere else on the disk, or
downloading
https://s3.amazonaws.com/gtfs-rt-validator/travis_builds/gtfs-rt-validator-1.0-SNAPSHOT.jar
and running from the directory it downloads to. The steps I mentioned above
may not be enough depending on how your build environment is structured.

**Comment by mohangandhiGH** [comment]
Yes, I will do that.

**Comment by mohangandhiGH** [comment]
@barbeau I think the problem is in accessing the "webroot" directory. When we try to access the index file from `target/classes/webroot` folder as we gave the BASE_RESOURCE folder name as `./target/classes/webroot` in **Main.java** file in our project, it fails as we don't have the BASE_RESOURCE folder. 
When I looked into the jar file downloaded from [ https://s3.amazonaws.com/gtfs-rt-validator/travis_builds/gtfs-rt-validator-1.0-SNAPSHOT.jar]( https://s3.amazonaws.com/gtfs-rt-validator/travis_builds/gtfs-rt-validator-1.0-SNAPSHOT.jar), it does not contain webroot in `target/classes` folder; in fact we don't have `target/classes` folder in the jar. We separately have the  "webroot" folder. So, when the application tries to access resources in `target/classes/webroot`, it fails.

**Comment by barbeau** [comment]
Also, for steps, you might need to run mvn clean first too. 

Yes, I believe that is the root cause. The target directory is intended to be the staging location for files before they get included into the JAR, so that's not the right place for resources. I believe they should be under main/resources folder or something similar so they get bundled into the JAR itself.  I believe there are a few SO questions about this related to embedded web apps and Jetty that I saw when quickly Google goes this earlier.

**Comment by barbeau** [comment]
Some of this appears to be configured in pom.xml too for Jetty.

**Comment by barbeau** [comment]
I believe this issue will affect https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/181 as well - we'll need to determine where to write the static validator output so it's accessible to the webapp.

**Comment by barbeau** [comment]
In terms of steps to reproduce - the JAR file generated by Travis and uploaded to S3 (https://s3.amazonaws.com/gtfs-rt-validator/travis_builds/gtfs-rt-validator-1.0-SNAPSHOT.jar) is generated with the `mvn install` command, and then it copies the JAR from `$HOME/.m2/repository/edu/usf/cutr/gtfs-rt-validator/1.0-SNAPSHOT` to S3.  So running `mvn clean` and then `mvn install` and grabbing the JAR from your local Maven repo location (similar path to the above) should give you the same type of JAR without the target directory files.
