### ISSUE TITLE
Integrate gtfs-validator-webapp UI for static GTFS validation results

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/gtfs-realtime-validator#23]
laidig-webapp provides a way to view the static GTFS validation report via a web UI. It's better if we integrate this feature in gtfs-realtime-validator, so that a user can have better view of the static validation report before running the real-time validation.

**Comment by jmfield2** [comment]
For using maven to automatically perform nodejs/npm or other tasks, you can use the plugin I added here: 

https://github.com/CUTR-at-USF/usf-mobullity/pull/336/files

**Comment by barbeau** [comment]
It seems one way to use the laidig webapp directly from the laidig gtfs-validator project is https://github.com/components/components.  This is how the existing gtfs-validator project pulls in some of it's web UI dependencies:
https://github.com/laidig/gtfs-validator/blob/master/gtfs-validator-webapp/component.json

**Comment by barbeau** [comment]
@sheldonabrown and @laidig - we'd like to include the gtfs-validator web UI in our project, so users of the gtfs-realtime-validator can see the static validation output in the gtfs-realtime validation UI (some problems in real-time feeds are caused by issues we'd want to validate in the static feeds).

Do you know what the best practice is in terms of referencing the gtfs-validator-webapp in this project as a dependency, vs. copying the files for the web UI into this project?

**Comment by mohangandhiGH** [comment]
@barbeau I have found an example online on how to download a specific github project file using maven download plugin. You can view it in the URL pasted below.
http://stackoverflow.com/questions/2741806/maven-downloading-files-from-url

I have tested with the solution provided in the URL and I was able to download files by mentioning each file separately in the configuration section.
Can you please comment your thoughts on using this plugin to bring laidig-webapp files.

**Comment by barbeau** [comment]
This would work if we don't find another option. The main downside of this is that if any file names change or are added in the gtfs-validator project it will break ours. I'd prefer to use something a little more stable that would build/reference the project as a whole so it's more flexible to changes.

**Comment by barbeau** [comment]
It looks like this issue in the gtfs-validator project is blocking us from seeing static validation results - https://github.com/conveyal/gtfs-validator/issues/17.

**Comment by barbeau** [comment]
I opened a new issue here for loading the gtfs-validator project output - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/114.
