### ISSUE TITLE
GTFS-rt - are stop_time_update.SKIPPED values propagated downstream?

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#26]
See https://groups.google.com/forum/#!topic/gtfs-realtime/teaI9X1FoGE.

**Comment by barbeau** [comment]
An analysis of how many agencies use the SKIPPED value for any StopTimeUpdate would be useful.

**Comment by minhhpham** [comment]
We performed an analysis using [transit-feed-quality-calculator](https://github.com/CUTR-at-USF/transit-feed-quality-calculator) on 9/29/2018 and found 6 agencies that use NO_DATA:


Feed | Location
-- | --
Metro Transit Trip Updates | Madison, WI, USA
Thunder Bay Transit Trip Updates | Thunder Bay, ON, Canada
Nashville MTA Trip Updates | Nashville, TN, USA
OVapi Train Trip Updates | The Netherlands
OVapi Trip Updates | The Netherlands
CT Transit Hartford Trip Updates | Connecticut, USA
VIA Trip Updates | San Antonio, TX, USA
ETS Trip Updates | Edmonton, AB, Canada
YRTViva Trip Updates | York, Toronto, ON, Canada
MetroTransit Trip Updates | Halifax, NS, Canada
Kingston Transit Trip Updates | Kingston, ON, Canada
MBTA Trip Updates | Boston, MA, USA

**Comment by minhhpham** [comment]
Snapshots of these feeds are available at https://gist.github.com/minhhpham/65dafc594ff8a1fafca30fe0319eed88

**Comment by minhhpham** [comment]
An update when contacting what agencies mean when using skipped:

- Kingston, ETS, ThunderBay, MTA, OVapi, VIA, and MBTA provide entire `stop_sequence ` in their `trip_update`, so their intention is clear.
- Metro Transit: no email yet
- CT Transit: waiting for response

**Comment by barbeau** [comment]
I've opened a proposal in PR at https://github.com/google/transit/pull/139

**Comment by barbeau** [comment]
https://github.com/google/transit/pull/139 was approved - new defined behavior is that SKIPPED values are not propagated, but delays (including those calculated from `time` values) are propagated over SKIPPED stops.
