### ISSUE TITLE
What should consumer behavior for stop_time_updates with NO_DATA be?

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#285]
See https://groups.google.com/d/msg/gtfs-realtime/hGxnOLR3cDA/Rsi3TT6aAQAJ.

A consumer said:

>The way I interpret NO_DATA is that I just revert to the schedule and do not propagate any delays so a user would just see the scheduled time. If however, the last entry in a StopTimeUpdate is SCHEDULED I do propagate delays.
The interpretation you give may make more sense but I wonder why a provider would just not leave the last entry as SCHEDULED in this case and allow the consumer propagate.
>
>Taking YRT/Viva which you are familiar with as an example, they seem to provide predictions for all of their stops on a trip for the majority of cases. There are perhaps 10% of cases where you see NO_DATA against a stop and nothing after. This suggests to me that 
when they are confident of propagating delays they fill them in for you but when they are not they use NO_DATA. 
>
>A best practice at least that the provider propagates would probably clear a lot of confusion and result in various implementations being closer to each other

My response:

>I agree, AFAIK the consumer behavior for NO_DATA isn't well specified at this point, so I think having some best practices around this would definitely help clarify things.
>
>GTFS-realtime best practices in general are on my TODO list as well, hopefully as an extension of the recent GTFS Best Practices effort (http://gtfs.org/best-practices/).

**Comment by barbeau** [comment]
An analysis of how many agencies use the NO_DATA value would be useful.

**Comment by barbeau** [comment]
Thanks @minhhpham!  Could you please add a few snippets of the feeds here in comments so we can see examples for how `NO_DATA` is used?  For example, is it the only `stop_time_update`, or does it appear in between other `stop_time_updates`?

**Comment by minhhpham** [comment]
Here's a snippet from GRT:
```
entity {
  id: "1659555"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "1659555"
      start_time: "17:15:00"
      start_date: "20180927"
      route_id: "76"
    }
    stop_time_update {
      stop_sequence: 1
      stop_id: "1744"
      schedule_relationship: NO_DATA
    }
  }
}
entity {
  id: "1659553"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "1659553"
      start_time: "16:15:00"
      start_date: "20180927"
      route_id: "76"
    }
    stop_time_update {
      stop_sequence: 14
      stop_id: "2047"
      schedule_relationship: NO_DATA
    }
  }
}
entity {
  id: "1659554"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "1659554"
      start_time: "16:45:00"
      start_date: "20180927"
      route_id: "76"
    }
    stop_time_update {
      stop_sequence: 1
      stop_id: "1744"
      schedule_relationship: NO_DATA
    }
  }
}
```
I'm not sure what this information means. I guess the trips are cancelled, but that could have been done with `TripDescriptor.ScheduleRelationship = CANCELED`

**Comment by minhhpham** [comment]
A few more from YRT/Viva:
```
entity {
  id: "1244151"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "1244151"
      start_time: "15:45:00"
      start_date: "20180927"
      route_id: "981"
    }
    stop_time_update {
      stop_sequence: 17
      stop_id: "9842"
      schedule_relationship: NO_DATA
    }
  }
}
entity {
  id: "1243974"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "1243974"
      start_time: "15:35:00"
      start_date: "20180927"
      route_id: "980"
    }
    stop_time_update {
      stop_sequence: 24
      stop_id: "641"
      schedule_relationship: NO_DATA
    }
  }
}
entity {
  id: "1244239"
  is_deleted: false
  trip_update {
    trip {
      trip_id: "1244239"
      start_time: "16:00:00"
      start_date: "20180927"
      route_id: "981"
    }
    stop_time_update {
      stop_sequence: 20
      stop_id: "717"
      schedule_relationship: NO_DATA
    }
  }
}
```

**Comment by barbeau** [comment]
Thanks @minhhpham!  Could you actually add examples for the rest of the agencies too?  I'm curious if everyone is using `schedule_relationship: NO_DATA` for the only `stop_time_update` in the trip (which appears to be the case of the above?), or if some are using it in the middle of other `stop_time_updates`.

**Comment by minhhpham** [comment]
Here are the feeds that have `schedule_relationship: NO_DATA`: https://gist.github.com/minhhpham/f062046998f0b8b0631726e45c924bc9.
Some of them (like Barrie) have NO_DATA in the middle of many stop_time_updates

**Comment by minhhpham** [comment]
OVapi and YRT confirmed that NO_DATA means no real-time information and is not a mean to propagate delay.

**Comment by barbeau** [comment]
We had a proposal accepted to clarify this in the spec at https://github.com/google/transit/pull/121, so this issue can be closed.
