### ISSUE TITLE
W002 on vehicle id is maybe useless

### ISSUE THREAD

**Issue by pbougue** [CUTR-at-USF/gtfs-realtime-validator#314]
**Summary:** 

Getting a warning on Sherbrooke's TripUpdate feed on vehicle_id while I don't need it

**Steps to reproduce:** 

When running validator on Sherbrooke:
* GTFS: https://www.donneesquebec.ca/recherche/dataset/e82b9141-09d8-4f85-af37-d84937bc2503/resource/4a5ace5b-5620-4513-93de-3e3d2b8b9f3a/download/gtfsstsherbrookeaut20170731.zip
* GTFSrt: http://67.212.79.244/civilia/STS/pb/tripUpdates.pb

I get a W002 : https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md#W002
But I don't need it at all, I can't relate it to GTFS.

So I open the discussion on the need for that warning.

**Expected behavior:** 

To my knowledge, remove that W002 warning.

It's only a warning, so it's not so important, I mostly open it to track if others are "impacted".
This issue might also be in the GTFSrt v2 specification repository.

I wonder what we are supposed to do with that field, but if it's in GTFSrt I guess it's usefull.
Not sure it deserves a warning.

Feel free to close it if nothing comes out of this, no problem.

**Comment by barbeau** [comment]
As https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md#W002 says:

>Populating vehicle_ids in TripUpdates is important so consumers can relate a given arrival/departure prediction to a particular vehicle.

So if you have both VehiclePositions and TripUpdates, vehicle_id is the only way to know which predictions came from which vehicle.

**Comment by pbougue** [comment]
The cases where I may see an interest are new trips not planned in base-schedule GTFS, and maybe to anticipate delay on other trips served by the same vehicle.

Otherwise, I guess the main need is to link prediction/position to a stop-sequence, and so to the base-GTFS's trip. And vehicle_id does not help with that.

Anyway, no problem letting it, it was more seen as an open discussion.

**Comment by barbeau** [comment]
Sure!  More discussion is always welcome :+1:
