### ISSUE TITLE
Is "1" a valid gtfs_realtime_version?

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#318]
**Summary:** 

TriMet currently has a GTFS-realtime header that looks like:

~~~
header {
  gtfs_realtime_version: "1"
  timestamp: 1517327681
}
~~~

Our rule [E038](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md#E038) currently only allows `1.0` and `2.0` as valid GTFS-realtime versions.

In the .proto, `gtfs_realtime_version` is a string, which means that either could potentially be a valid field value, although the GTFS-realtime spec current says that:
>The current version is 2.0

Also, the [git history](https://github.com/google/transit/commit/eb4b243513abdca8efeaefbf8c264d9d1072ffb6#diff-d95a86ce7ac54ab6a4d448465a6f5c5b) shows that it previously said:
>The current version is 1.0

We should clarify whether the `.0` is a required part of the version number.

**Steps to reproduce:** 

Look at any of TriMet's GTFS-realtime feeds

**Expected behavior:** 

Have a `gtfs_realtime_version` version number that includes `.0`

**Observed behavior:** 

The `gtfs_realtime_version` is `1`

**Platform:** 

N/A

**Comment by barbeau** [comment]
The bigger issue here is versioning of the GTFS-realtime spec - currently there isn't a tagged release that would give a precise definition to actual version numbers.

From a typical producer/consumer perspective, this means that they can land on the Google GTFS-realtime Reference page:
https://developers.google.com/transit/gtfs-realtime/reference/

...which says that:

>Version 2.0 of the feed specification is discussed and documented on this site.

...but there is no easy way to go back and see what the full GTFS-realtime v1.0 spec looked like, unless you understand Git/GitHub and can dig back through the PR that created GTFS-realtime v2.0:
https://github.com/google/transit/pull/64

...find the merged commit:
https://github.com/google/transit/commit/eb4b243513abdca8efeaefbf8c264d9d1072ffb6

...and then click on the "View" button for `reference.md`, which would then give you the reference document at that commit:
https://github.com/google/transit/blob/eb4b243513abdca8efeaefbf8c264d9d1072ffb6/gtfs-realtime/spec/en/reference.md

It needs to be much easier to find the official "v1.0", and for us to have an official list of releases that can be matched exactly.

**Comment by barbeau** [comment]
It would be useful to analyze how many agencies other than TriMet are providing values other than  `1.0` and `2.0` for `gtfs_realtime_version` (i.e., rule [E038](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/RULES.md#E038) shows up when their feed is validated), as well as what values they are using for `gtfs_realtime_version` in their feeds.

**Comment by minhhpham** [comment]
There are only 2 agencies that don't use "1.0" or "2.0" as version. Those are Rhode Island Public Transit Authority and Capital Metro. They both use "1" as version.

**Comment by barbeau** [comment]
Thanks @minhhpham!  For the above agencies using other values, what values are they using?  I know TriMet is `1`, but I don't know the other 3.

**Comment by minhhpham** [comment]
The other 3 also have `gtfs_realtime_version: "1"`

**Comment by barbeau** [comment]
https://github.com/google/transit/pull/130 was approved and merged into the spec, so we can close this issue.  The official GTFS-rt spec now considers the only valid GTFS-rt version numbers to be `1.0` and `2.0`, which matches our validator.
