### ISSUE TITLE
SQL injection vulnerability for hosted instances of the webapp

### ISSUE THREAD

**Issue by skjolber** [CUTR-at-USF/gtfs-realtime-validator#322]
**Summary:** 

Manual construction of queries adding strings together is security hole

**Steps to reproduce:** 

See all createQuery(..) method calls.

**Expected behavior:** 

Use builder to add parameters. 

**Observed behavior:** 

String appending

**Platform:** 

Java

**Comment by barbeau** [comment]
@skjolber Thanks for flagging this!

**Comment by barbeau** [comment]
@skjolber https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/324 should fix this if you want to have a look.  I'm going to test a bit before merging, any other eyes on this are welcome.
