### ISSUE TITLE
Dead end hyperlink for Dutch GTFS

### ISSUE THREAD

**Issue by AntoineGrapperon** [CUTR-at-USF/gtfs-realtime-validator#339]
http://gtfs.openov.nl/gtfs/gtfs-openov-nl.zip sends to a 404 page.

http://gtfs.openov.nl/gtfs-rt/gtfs-openov-nl.zip could be the correct URL? (I am guessing the server got re-arranged a little since you first wrote this list)

EDIT - I was actually not reading the gtfs-realtime-validator README file, whic I thought to be out of date, I was reading an issue related to it (see [here](https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/123) sooooo...  Not an issue!

**Comment by barbeau** [comment]
@AntoineGrapperon Thanks for the heads up!  I just updated the issue too.
