### ISSUE TITLE
UtilTest.testGetElapsedTimeString fails as number formatting depends on locale 

### ISSUE THREAD

**Issue by hbruch** [CUTR-at-USF/gtfs-realtime-validator#349]
**Summary:** 

UtilTest.testGetElapsedTimeString fails on German locale

**Steps to reproduce:** 

With a German locale, run `mvn package`

**Expected behavior:** 

Test should succeed

**Observed behavior:** 

UtilTest.testGetElapsedTimeString fails:

ERROR] Failures:
[ERROR]   UtilTest.testGetElapsedTimeString:321 expected:<2[.]5 seconds> but was:<2[,]5 seconds>

**Platform:** 
MacOS, Java 1.8, locale de_DE.UTF-8

**Comment by barbeau** [comment]
Re-opening, per https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/350#issuecomment-506514459
