### ISSUE TITLE
GTFS-Feed-Error not reported

### ISSUE THREAD

**Issue by hbruch** [CUTR-at-USF/gtfs-realtime-validator#351]
**Summary:** 

When downloading an erroneous GTFS Feed, the download fails without further information.

**Steps to reproduce:** 

Provide e.g. [this (erroneous) GTFS-Feed](https://www.vrn.de/mam/service/downloads/vrn_gtfs.zip), which contains stops without lot/lat in Step 1 as GTFS Feed and the [corresponding GTFS-RT](http://145.253.183.19:7777/) as GTFS-RT in Step 2.

**Expected behavior:** 

Validator displays a specific error message in the browser, or at least in the logs.

**Observed behavior:** 
Import fails, a misleading error message "GTFS Feed Error. Not Found. Can't read GTFS zip file from disk" is displayed in the browser, no additional info is logged in the console.

The exception is consumed silently in [GTFSFeed:288](https://github.com/CUTR-at-USF/gtfs-realtime-validator/blob/master/gtfs-realtime-validator-webapp/src/main/java/edu/usf/cutr/gtfsrtvalidator/api/resource/GtfsFeed.java#L288). 

**Platform:** 
n.a.

**Comment by barbeau** [comment]
@hbruch Thanks for the bug report! I don't think I'll be able to resolve this issue as quickly but we'll take a look.

**Comment by barbeau** [comment]
Fixed in https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/376
