### ISSUE TITLE
Check that route id, trip id, stop id, stop sequence match the ids in GTFS

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#36]
For TripUpdate. This would generate an error.  See https://groups.google.com/d/msg/gtfs-realtime/qNc7ButQbW8/tDwanvClBQAJ.

**Comment by mohangandhiGH** [comment]
@barbeau checking trip id in TripUpdate feed to match against GTFS data is implemented as error 'e003'. Do we need to implement route id, stop id and stop sequence fields as part of 'e003' implementation or implement as separate errors for each of these fields? 


To confirm, as per the above provided [link](https://groups.google.com/d/msg/gtfs-realtime/qNc7ButQbW8/tDwanvClBQAJ), we need to 
1)  check route id, trip id, stop id, stop sequence to match in GTFS data and TripUpdate feed
2)  check trip id and stop id to match in GTFS data and VehiclePositions feed

**Comment by barbeau** [comment]
@mohangandhiGH Good question.  For now let's do all of these as part of e003, and I guess we'll generalize the description of that error to "All IDs provided in the GTFS-rt feed must match the GTFS data"

In terms of the scope of the rule, I'd approach this by looking at the GTFS-rt spec for Trip Updates, Vehicle Positions, and Service Alerts:

* [Trip Updates](https://developers.google.com/transit/gtfs-realtime/reference/TripUpdate)
* [Vehicle Positions](https://developers.google.com/transit/gtfs-realtime/reference/VehiclePosition)
* [Alerts](https://developers.google.com/transit/gtfs-realtime/reference/Alert)

...and for any child element that contains an ID that references GTFS data, that ID should match the GTFS data.

So, for example, under TripUpdate there is a [TripDescriptor](https://developers.google.com/transit/gtfs-realtime/reference/TripDescriptor), which contains a `trip_id`, `route_id`, and `direction_id`.  All of these reference the GTFS data and should match (note here that under certain conditions the `start_time` field should also match GTFS, but because it's not an ID, and it's conditional based on the type of trip, let's leave `start_time` matching to another rule - I believe https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/37 and https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/48 cover this, for different conditions).

**Comment by barbeau** [comment]
To update this issue, here's what's already implemented:
* trip IDs are covered under `E003`
* route IDs are covered under `E004`
* stop IDs are covered under `E011`
* stop sequence presence is defined as `E009` in the code but not implemented.  Also does not cover matching GTFS data as-is.
* `E002` covers stops out of stop_sequence order

So we should implement the remaining items discussed above as separate rules, not grouped under `E003` as I mentioned earlier in this thread.

**Comment by barbeau** [comment]
I've opened https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/160 for matching direction_id, and https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/161 for stop_sequence and stop_id matching the GTFS data.  So, all sub-items for this umbrella issue are now implemented or covered by individual open issues, so I'm closing this.
