### ISSUE TITLE
official Docker image, automatically built

### ISSUE THREAD

**Issue by derhuerst** [CUTR-at-USF/gtfs-realtime-validator#374]
I'd like to use this tool via a canonical, up-to-date Docker image. By having a `Dockerfile` in this repo, we can configure the [Docker Hub to automatically build on push](https://docs.docker.com/docker-hub/builds/).

One of the existing Docker images is outdated ([`transitscreen/gtfs-realtime-validator-docker`](https://hub.docker.com/r/transitscreen/gtfs-realtime-validator-docker/tags)).

With every "3rd-party" Docker image, there will always be a drift in actuality between this repo and the Docker images.

---

If you agree, I'd like to PR [the `thzinc` `Dockerfile`](https://github.com/thzinc/gtfs-realtime-validator/blob/1ed7e9c0238c83c8088b7d7acaf79744d3948a43/Dockerfile) into this repo. You'd have to configure automated builds in the Docker Hub.

**Comment by barbeau** [comment]
@derhuerst Sure, I'd like 1st party support for Docker in this repo. PRs are welcome, although if it's from @thzinc repo it would be best if it comes from him (or with his permission) so it's a clean contribution.

@thzinc any thoughts on contributing your Docker file?

**Comment by derhuerst** [comment]
@thzinc's repo has no change to the license. I'd just PR his `Dockerfile`.

**Comment by thzinc** [comment]
I’m totally cool with contributing this way. I won’t be at a computer for at least several hours. If this is something you want to move on quickly, go for it. Otherwise, I can submit a PR tonight PDT.

**Comment by barbeau** [comment]
@thzinc That's great - no rush! Sometime this weekend is fine. 👍

**Comment by barbeau** [comment]
Including https://github.com/thzinc/gtfs-realtime-validator/commit/1ed7e9c0238c83c8088b7d7acaf79744d3948a43 would be great, although preferably as a separate PR as they are unrelated.

**Comment by thzinc** [comment]
@barbeau, done and done.

**Comment by barbeau** [comment]
Awesome, thanks!

**Comment by derhuerst** [comment]
@barbeau Can you enable an automated Docker image build for this repo?

**Comment by barbeau** [comment]
I just went through the config for this, I believe it should be done at https://hub.docker.com/repository/docker/cutrusf/gtfs-realtime-validator.

I'm relatively new to Docker, so let me know if something doesn't look right.

**Comment by derhuerst** [comment]
Looks good, thank you!

I'd set the [`ENTRYPOINT`](https://docs.docker.com/engine/reference/builder/#entrypoint) to `["-Djsee.enableSNIExtension=false", "-jar", "gtfs-realtime-validator-webapp-1.0.0-SNAPSHOT.jar"]` for a better UX though.

**Comment by barbeau** [comment]
@derhuerst Ok - could you PR this?
