### ISSUE TITLE
GTFS Feed Error with 511 SF API

### ISSUE THREAD

**Issue by mcplanner** [CUTR-at-USF/gtfs-realtime-validator#388]
**Summary:** 

I'm trying to review feeds from the 511 SF API, and, while it's possible to download static feeds directly, the validator is failing on this step.

**Steps to reproduce:** 

Static: http://api.511.org/transit/datafeeds?api_key=[key]&operator_id=3D
RT: http://api.511.org/transit/tripupdates?api_key=[key]&agency=3D

**Expected behavior:** 

What did you expect the application to do?

Process the static feed and monitor the API.

**Observed behavior:** 

GTFS Feed Error: "Server Error. Request failed." 

**Platform:** 

What is the operating system and Java version of your machine?  What browser (Chrome, Internet Explorer, Firefox)did you use?

- OS: macOS Catalina 10.15.6
- Java version: 11.0.5
- Chrome version: 86.0.4240.80

**Comment by mcplanner** [comment]
It's not failing consistently. It worked on the first several, then started giving errors on the vehicle position feeds half the time. If I pasted the VP URL into the browser, I got an error message that I've exceeded the 60 in 3600 call limit. Then I started seeing issues with the static feed, though I'm having no issues accessing that URL through the browser directly.

**Comment by barbeau** [comment]
@mcplanner Thanks for opening the issue! Sounds like this may be an API key rate limiting issue? I'm assuming the above error message means that you can't query the feed more often than every 60 seconds? IIRC the web interface has a 10 second default refresh rate. Could you try waiting a few hours and trying again with a refresh rate greater than 60 seconds?

**Comment by mcplanner** [comment]
Thanks for the quick response! It sounds like maybe two separate issues, because I can still download the static file through the browser directly. First run of the morning, going at 60 seconds, and working well so far. Thanks!

**Comment by barbeau** [comment]
@mcplanner Ok, sounds good. I'm going to close the issue, but feel free to re-open if you hit the problem again.
