### ISSUE TITLE
Dependency Error for conveyal gtfs validator

### ISSUE THREAD

**Issue by e-lo** [CUTR-at-USF/gtfs-realtime-validator#399]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:**  Build the Dockerfile

**Expected behavior:**  Successful build

**Observed behavior:** 
```
#13 285.1 [ERROR] Failed to execute goal on project gtfs-realtime-validator-webapp: Could not resolve dependencies for project edu.usf.cutr:gtfs-realtime-validator-webapp:jar:1.0.0-SNAPSHOT: 

Failed to collect dependencies at com.conveyal:gtfs-validation-lib:jar:0.1.7-SNAPSHOT: 

Failed to read artifact descriptor for com.conveyal:gtfs-validation-lib:jar:0.1.7-SNAPSHOT: 

Could not transfer artifact com.conveyal:gtfs-validation-lib:pom:0.1.7-SNAPSHOT from/to maven-default-http-blocker (http://0.0.0.0/): 

Blocked mirror for repositories: [conveyal-releases-mvn-repo (http://build.staging.obanyc.com/archiva/repository/releases/, default, releases+snapshots), conveyal-snapshots-mvn-repo (http://build.staging.obanyc.com/archiva/repository/snapshots/, default, releases+snapshots)]
```

**Platform:**  Docker

**Comment by barbeau** [comment]
Thanks for the report @e-lo!

From a quick look it looks like this is because the maven repository hosting the Conveyal gtfs-validation-lib is hosted at HTTP and not at the secure HTTPS:
http://build.staging.obanyc.com/archiva/repository/releases/

The equivalent HTTPS link doesn't seem to work:
https://build.staging.obanyc.com/archiva/repository/releases/

I opened a PR here to see if we can get CI to pass with the HTTPS URLs anyway:
https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/400

If that doesn't work other possibilities are:
1. Configure Maven to allow HTTP for this repo - https://stackoverflow.com/a/67441519/937715
2. Get Conveyal to host the Maven repo at HTTPS
3. Remove depedency on gtfs-validation-lib and replace it with MobilityData gtfs-validator

**Comment by barbeau** [comment]
I just set up a simple GitHub Action to see if changing to HTTPS works in PR https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/401 (the other PR used Travis which isn't working anymore).

**Comment by barbeau** [comment]
Nope, HTTPS URL doesn't work:

```
Error:  Failed to execute goal on project gtfs-realtime-validator-webapp: Could not resolve dependencies for project edu.usf.cutr:gtfs-realtime-validator-webapp:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at com.conveyal:gtfs-validation-lib:jar:0.1.7-SNAPSHOT: Failed to read artifact descriptor for com.conveyal:gtfs-validation-lib:jar:0.1.7-SNAPSHOT: Could not transfer artifact com.conveyal:gtfs-validation-lib:pom:0.1.7-SNAPSHOT from/to conveyal-releases-mvn-repo (https://build.staging.obanyc.com/archiva/repository/releases/): transfer failed for https://build.staging.obanyc.com/archiva/repository/releases/com/conveyal/gtfs-validation-lib/0.1.7-SNAPSHOT/gtfs-validation-lib-0.1.7-SNAPSHOT.pom: Connect to build.staging.obanyc.com:443 [build.staging.obanyc.com/3.94.110.216] failed: Connection refused (Connection refused) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :gtfs-realtime-validator-webapp
Error: Process completed with exit code 1.
```

**Comment by e-lo** [comment]
> Remove dependency on gtfs-validation-lib and replace it with MobilityData gtfs-validator

Obviously this seems like the end goal solution, but if this is a ways out an interim fix would also be very much appreciated if we can find one that works.

**Comment by barbeau** [comment]
@e-lo This issue should now be fixed in the main branch if you want to give it another try!
