### ISSUE TITLE
Check that non-revenue trips/stops aren't included in TripUpdates and VehiclePositions feeds

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#44]
Sometimes agencies include trips that are for training or non-revenue trips/stops in their GTFS-realtime feeds. These trips/stops are not included in the GTFS schedule data. These are not regularly scheduled trips/stops and are not available to the public. These trips/stops should not be included in the GTFS-realtime feeds.

This would generate a warning.  See https://groups.google.com/d/msg/gtfs-realtime/qNc7ButQbW8/tDwanvClBQAJ.

**Comment by barbeau** [comment]
@ritesh-warade-ibigroup For these non-revenue trips and stops that shouldn't be in the GTFS-rt feed - how do you know that they are non-revenue?  Is it just stop_ids and trip_ids that appear in the GTFS-rt feed but not in the GTFS data?  Or is there another way to determine that they are non-revenue?

Trying to determine the best way to translate this into a validation rule.

**Comment by ritesh-warade-ibigroup** [comment]
That sounds correct: non-revenue trips and stops that shouldn’t be in the GTFS-rt feed will not appear in the GTFS and are not marked as ADDED in the ScheduleRelationship field.

We have seen that during our work with agencies - there were extra driver trips that appeared in GTFS-rt but not in GTFS, OR there is data about stops in ‘staging areas’.

**Comment by barbeau** [comment]
Thanks @ritesh-warade-ibigroup!  

So for trips I believe this is just an extension of our existing rule `E003` for trip_ids - we just need to check for `ADDED`.

And, we'll add a new rule for stop_ids not appearing in GTFS data.

**Comment by barbeau** [comment]
Actually, looks like we're already checking for `stop_ids` that don't exist in GTFS data in `E011`, the description of the rule is just incorrect.  I'm fixing that in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/147.

I've implemented the check for trip_id `ADDED` schedule_relationship at https://github.com/CUTR-at-USF/gtfs-realtime-validator/commit/571eda5894e6962563f59ad4fdea8e749250286b.

So, we can close this issue as both cases are covered.
