### ISSUE TITLE
Stop_times.timepoint should not be specified for frequencies.txt exact_times=0 trips

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#55]
There is an optional field in stop_times.txt `timepoint` that is used to specify timepoint that a transit vehicle should strictly adhere to (e.g., hold if they are running early).  If a trip is defined in frequencies.txt with the `exact_times=0` value, then it is a frequency-based trips, which means that a schedule doesn't exist.  Therefore, frequency-based trips should NOT have any timepoint=1 values in stop_times.txt - the field should either be `0` or blank - to do this would be an error.

See discussion at https://github.com/google/transit/pull/47#issuecomment-278360876.

I believe this is purely a static GTFS issue, so we should open a new issue on the conveyal gtfs-validator project and implement the rule there:
https://github.com/conveyal/gtfs-validator

**Comment by mohangandhiGH** [comment]
@barbeau Opened the same new issue in https://github.com/conveyal/gtfs-validator

**Comment by barbeau** [comment]
Thanks! Could you link that issue here (just paste URL into the comment)?

**Comment by mohangandhiGH** [comment]
Here is the link to the issue in conveyal project 
https://github.com/conveyal/gtfs-validator/issues/27
