### ISSUE TITLE
Check that timestamps are in POSIX time in all feed elements

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/gtfs-realtime-validator#57]

**Comment by barbeau** [comment]
+1 - I've seen several feeds with timestamps in milliseconds past epoch, instead of seconds past epoch (POSIX).

**Comment by barbeau** [comment]
I'm working on this, as part of the new structure to validate multiple rules in the same class (thanks @mohangandhiGH for starting work on this!) - it's currently listed as E01 in `ValidationRules`.  I'll open a PR shortly.
