### ISSUE TITLE
Ability to batch process local feed archive

### ISSUE THREAD

**Issue by danp** [CUTR-at-USF/gtfs-realtime-validator#68]
I have a utility that polls a GTFS-RT feed and archives to S3 so later they can be downloaded for analysis. For example, here's what the structure looks like:

```
% find TripUpdates -type f | sort | head -n10
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-57-20Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-57-35Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-57-51Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-06Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-21Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-36Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-58-51Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-59-06Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-59-21Z.pb
TripUpdates/2017/02/09/14/TripUpdates-2017-02-09T14-59-36Z.pb
```

The tool names the path and files based on the feed header timestamp.

It would be nice if I could run the validator against all these as if it had polled a single URL and received them in succession.

**Comment by barbeau** [comment]
Thanks @danp!  This would be nice - we'll look at adding it.

**Comment by barbeau** [comment]
@danp Could you attach around 10 pb files here so we have some test data to work off of from your exact use case?

**Comment by danp** [comment]
Here's two hours worth:

[trip-updates.zip](https://github.com/CUTR-at-USF/gtfs-realtime-validator/files/794014/trip-updates.zip)

**Comment by danp** [comment]
And the associated static data can be downloaded from http://www.halifax.ca/opendata/transit.php.

**Comment by barbeau** [comment]
Thanks!

**Comment by barbeau** [comment]
@danp Is your polling/archiving tool to S3 open-source?  I'd like to set up something similar, ideally so it can be spun up for a large number of agencies.

**Comment by danp** [comment]
Pushed my very WIP repo up to https://github.com/danp/catchbus. The archiver is at https://github.com/danp/catchbus/blob/master/cmd/gtfs-rt-archive/main.go. It currently only handles one set of feed URLs but could probably be pretty easily extended to many sets, each going to a different bucket or prefix.

**Comment by barbeau** [comment]
Off the top of my head I can't think of any reason why bulk archived feed processing can't be parallelized, so we should look at the Java [ThreadPoolExecutor](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#ThreadPoolExecutor(int,%20int,%20long,%20java.util.concurrent.TimeUnit,%20java.util.concurrent.BlockingQueue,%20java.util.concurrent.RejectedExecutionHandler)) for implementation.  This looks like a good overview with some examples:
http://www.java2blog.com/2016/12/java-threadpoolexecutor-example.html

We should make things like max pool size, core pool size, and keepAliveTime configurable from command line arguments to allow flexibility for execution on machines with different numbers of CPUs/cores.

**Comment by barbeau** [comment]
If we support loading archived feeds, we'll need to figure out how to handle rules like `W008` that compare GTFS-rt timestamps to the current system time.

Related issue - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/153.

**Comment by barbeau** [comment]
As part of implementing #153 I added the ability to pass in the "current" system time to each validation rule, so this should allow us to batch process feeds and pass in the time at which the feed was archived (perhaps derived from system file timestamp or file name - TBD).

**Comment by barbeau** [comment]
WIP PR at https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/279.

@danp I ended up needing to process some archived GTFS-realtime protocol buffers files as part of debugging https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/259, so I went ahead and created a full-fledged batch processing mode.

Execution looks like:

`java -jar target/gtfs-rt-validator-1.0.0-SNAPSHOT.jar -batch yes -gtfs "D:\HART\google_transit.zip" -gtfsrealtimepath "D:\HART\gtfs-rt" -sort date`

See full description of command-line parameters and description of output at the WIP PR https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/259.

Could you please give it a try and see if it meets your needs?  Any suggestions for improvement are welcome too!

**Comment by barbeau** [comment]
Alright, batch processing should now be available in the master branch.

Full docs available in "Configuration Options->Batch processing" section in main README:
https://github.com/CUTR-at-USF/gtfs-realtime-validator#configuration-options
