### ISSUE TITLE
Validating stop_ids reference by GTFS-rt feed have a location_type of 0

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#7]
**Type:**  Error (Implicitly stated in the GTFS specifications)
**Description:** All stop_ids referenced in GTFS-rt feeds must have the "location_type" = 0
**Affected Feed Type(s):**  TripUpdate, VehiclePostion 
**Reference(s):** https://developers.google.com/transit/gtfs/reference?hl=en#stop_timestxt

**Notes:** Since checking if the stop_ids in the GTFS-rt feeds have a location type of 0 would mean that all stop_ids referenced in that iteration are valid, would we any need of checking the GTFS feed to see if, 
"If location_type is used in stops.txt, all stops referenced in stop_times.txt must have location_type of 0."?

**Comment by barbeau** [comment]
+1 for adding this rule

>would we any need of checking the GTFS feed to see if, 
"If location_type is used in stops.txt, all stops referenced in stop_times.txt must have location_type of 0."?

That's a good question.  IMO, we should check for this in our GTFS-rt validator, because even if a particular stop_id X isn't included in the GTFS-rt data, having X with location_type of 1 in the schedule data would affect how we propagate delays downstream.  In other words, when trying to propagate TripUpdates we'd hit an invalid stop in the stops_times.txt data.

**Comment by barbeau** [comment]
Also, +1  to @nipuna777 for the neatly formatting rule proposal :).

**Comment by nipuna777** [comment]
Thank you :) 

>In other words, when trying to propagate TripUpdates we'd hit an invalid stop in the stops_times.txt data.

Right. I'd never have caught that. So, should that be a seperate rule? 

Or can we just check for that rule(location_type is 0 in GTFS feed) since we are already checking to see whether all stop_ids are available on the GTFS feed?

**Comment by barbeau** [comment]
>So, should that be a seperate rule?

Yes - could be implemented either at load time when we validate the GTFS-specific rules, or when checking if all stops_ids are available in the GTFS feed.  I think for something like this that can be entirely validated on static GTFS data without needing the real-time data, it should be done at load time.

**Comment by nipuna777** [comment]
Got it. 
But, once the GTFS feed is checked to make sure that all stop_ids referenced in trips are of location_type is 0, is there any reason to check the Reatltime Feeds again for the same error? Would that not make this rule redundant? 

Or, can there be times when a Vehicle is at a stop which is not in the stop_times.txt?

**Comment by barbeau** [comment]
>But, once the GTFS feed is checked to make sure that all stop_ids referenced in trips are of location_type is 0, is there any reason to check the Reatltime Feeds again for the same error? Would that not make this rule redundant?

Good question - in most cases that I'm aware of yes, but I think there are some corner cases where it wouldn't be redundant.  One possibility is if you have a vehicle running that isn't currently assigned to a trip (and therefore no trip_id to reference), but for some reason the provider is still providing an estimate and a stop_id.  For example, in [TripDescriptor reference](https://developers.google.com/transit/gtfs-realtime/reference?hl=en#TripDescriptor):

>To specify all the trips along a given route, only the route_id should be set. Note that if the trip_id is not known, then station sequence ids in TripUpdate are not sufficient, and stop_ids must be provided as well.

So if a trip_id isn't provided, then we can't reference stop_times.txt, but stop_ids are still provided to us.

So it probably makes sense to keep it as a real-time rule as well, to avoid making assumptions with areas of the spec that aren't very clear or don't have strict requirements for required fields.

**Comment by nipuna777** [comment]
Got it. I'm making two new rules then.
I'll open another issue for checking the GTFS feed at loading time.
