### ISSUE TITLE
Displaying GTFS-rt errors

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/gtfs-realtime-validator#74]
**Summary:** 

While monitoring the GTFS realtime feed, the feed errors needs to be displayed.
Here is a sample screenshot of how the error might be displayed.
![image](https://cloud.githubusercontent.com/assets/17164961/23371445/2d617dc8-fce6-11e6-8100-ae0492564b00.png)

**Comment by barbeau** [comment]
Looks good! 

A few comments:
* First column title should be "ID", as it could be an error or a warning 
* Timestamp - I'd display this in 12hr time and include POSIX time next to it,  like "12:09:03 PM (1752857358565)“, with the time zone being the time zone from the GTFS data agency.txt.  I'd add the full timezone text as something that pops up when you hover over time. And I'd only add the date if the date is different from today (i.e., the feed monitoring has crossed into another day). And if we are showing a count of errors here (this is a summary of multiple errors), then the timestamp title should probably be something like "Last occurrence".

**Comment by barbeau** [comment]
And "Error Count" should just be "Count".

**Comment by mohangandhiGH** [comment]
@barbeau Updated based on your comments.
![image](https://cloud.githubusercontent.com/assets/17164961/23372966/dd7e6cfc-fceb-11e6-8edf-93a49ad25591.png)

**Comment by barbeau** [comment]
Looks good!  Let's go with this for now.
