### ISSUE TITLE
java.util.NoSuchElementException: No value present. 

### ISSUE THREAD

**Issue by scrudden** [CUTR-at-USF/gtfs-realtime-validator#75]
**Summary:** 

Get an exception "java.util.NoSuchElementException: No value present." when trying to use validator.

**Steps to reproduce:** 

Start and use the following inputs.

https://dl.dropboxusercontent.com/u/107527881/final_dt2.zip
http://www.dynamictime.org/api/v1/key/f78a2e9a/agency/ASC/command/gtfs-rt/tripUpdates
http://www.dynamictime.org/api/v1/key/f78a2e9a/agency/ASC/command/gtfs-rt/vehiclePositions

**Expected behavior:** 

Give me an error message with detail of what may be wrong with the GTFS.

**Observed behavior:** 
Failed with GTFS-Feed (error) but no detail.

**Other detail.**
Exception is coming from the FeedProcessor run() method.

**Comment by mohangandhiGH** [comment]
@scrudden The fix for this issue is created as PR https://github.com/conveyal/gtfs-validator/pull/29. Could you please wait and try after this PR is merged in https://github.com/conveyal/gtfs-validator.

**Comment by barbeau** [comment]
Thanks @scrudden!  We'll keep this open until the gtfs-validator fix is merged.

**Comment by barbeau** [comment]
https://github.com/conveyal/gtfs-validator/pull/29 is merged, so I'm going to close this issue.  It should be fixed in the Maven artifacts to be posted to the Conveyal repo shortly, and after that happens you can refresh your local Maven artifacts with `mvn clean install -U`.
