### ISSUE TITLE
Validating stop_id location_type where they are reference by  stop_times.txt 

### ISSUE THREAD

**Issue by nipuna777** [CUTR-at-USF/gtfs-realtime-validator#8]
**Type:**  Error
**Description:** If location_type is used in stops.txt, all stops referenced in stop_times.txt must have location_type of 0
**Affected Feed Type(s):**  GTFS feed 
**Reference(s):** https://developers.google.com/transit/gtfs/reference?hl=en#stop_timestxt

**Notes:** Should be checked at the initialization of the process.

**Comment by barbeau** [comment]
+1 for adding this rule.

Also discussed at https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/7#issuecomment-130361679.
