### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#9]
@nipuna777 Thanks for all your work on this project in the Google Summer of Code!

Could you provide a list of things you were able to accomplish, and what still needs to be done (by you or others) to bring this tool to a working state?

This will make it easier for others to see where we're currently at, and what still needs to be accomplished.

**Comment by barbeau** [comment]
cc @caywood

**Comment by nipuna777** [comment]
@barbeau Of course! Extremely sorry about the delay. I've been trying to do some work on the project but have been busy with university. 

Should I add this to the wiki of the project? I have a presentation this morning. I'll be updating this in the evening.

**Comment by barbeau** [comment]
@nipuna777 No worries, I saw that you were still contributing, but just wanted to get a sense of your plans, so that others can contribute to the project as well.

Yes, let's add a roadmap wiki, and we can keep that up to date.  If there are specific features/bugs that still need to be tackled that are easily isolated into their own issues, please open an issue for those and cross-reference in the wiki.

Thanks!

**Comment by nipuna777** [comment]
I've started a wiki page for the roadmap. 
https://github.com/CUTR-at-USF/gtfs-realtime-validator/wiki/Roadmap

I will be updating it soon in order to show all that needs to be done. I will try to break down the problems into smaller parts to make them easier to address.

**Comment by barbeau** [comment]
@nipuna777 Thanks!  I've created Github Milestones as well (v1, v2, v3 - according to your roadmap on the wiki), so when you create issues, please assign them to the milestone as relevant.

Also, could you indicate what you plan to work on in upcoming weeks, and what things you aren't working on?  We'd certainly welcome your continued contributions, but I also understand that you were only obligated to work on this as part of the Google Summer of Code.  So, it's ok if you can't tackle certain things - we'd just like to know so we can plan for others to work on them.

One easy way to indicate what you plan to work on is to create issues and assign them to yourself.  For other things you won't have time to work on, you can create the issue but not assign it.

**Comment by nipuna777** [comment]
Got it. the last few weeks have been a bit busy. But I will be able to work on this project for the next month about 4 hours a day. Starting today, I'll assign myself issues and start developing. 

Should I create issues that are for the later milestones as well? (such as going for a SPA architecture?)

**Comment by barbeau** [comment]
@nipuna777 Great!  Yes, please create issues for the later milestones too.  It makes it easier to pull up milestones and see all the related issues that are still open and need to be created for that milestone.

**Comment by barbeau** [comment]
This issue is very dated now, so I'm going to close it out.  For now we'll manage the roadmap via Github milestones.
