### ISSUE TITLE
Creating database schema using Hibernate

### ISSUE THREAD

**Issue by mohangandhiGH** [CUTR-at-USF/gtfs-realtime-validator#95]
**Summary:** 

Currently we use `createTables.sql` to create database schema. We need to change it to use Hibernate.

**Comment by barbeau** [comment]
Reason for this is that currently any time we change the database schema, we have to delete the database files otherwise operations fail.  See https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/77#issuecomment-286880440 for an example.
