### ISSUE TITLE
Only log validation warnings/errors for unique responses

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/gtfs-realtime-validator#96]
**Summary:** 

Currently, every time we poll the GTFS-rt feed we do the following in `BackgroundTask`:

1. Retrieve the GTFS-rt PB feed message
1. Hash it and compare it to the hash of the most recent GTFS-rt pb message in our local database for this feed URL
1. If the feeds are different, we set a boolean variable indicating that the new feed is unique (i.e., its the first time we've seen that instance of the feed)
1. Store the new feed message in our database
1. Run the new feed message through rule validation and log errors/warnings to database

We should change this so we only log rule validation warnings/errors on unique feeds.  Otherwise we're simply logging duplicate errors/warnings.

So, the process should change to:

1. Retrieve the GTFS-rt PB feed message
1. Hash it and compare it to the hash of the most recent GTFS-rt pb message in our local database for this feed URL
1. If the feeds are different, we set a boolean variable indicating that the new feed is unique (i.e., its the first time we've seen that instance of the feed)
1. Store the new feed message in our database
1. If the feed is unique (i.e., first time we've seen this exact message), run the new feed message through rule validation and log errors/warnings to database

(Note that https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/92 also changes the above process slightly to avoid storing duplicate PB messages in the database)

**Steps to reproduce:** 

1. Start the validator and enter GTFS and GTFS-rt feed

**Expected behavior:** 

Only log errors/warnings to database for the first time a new feed message is observed

**Observed behavior:** 

Errors/warnings are duplicated - the validation is run on every message returned by an HTTP request, instead of just the first instance of that message.

**Comment by mohangandhiGH** [comment]
@barbeau Do we need to validate the feed and don't log duplicate errors or no need of validating the duplicate field at all?

*  Considering first choice, I think, it does not have any advantage of validating the duplicate feed and not logging the errors.

*  For the second choice, we don't actually need to do anything except returning the `BackgroundTask`, if we found the feed to be validated in the current iteration is already validated in the previous iteration. This will make sure we are not logging duplicate errors.

Can you please share your thoughts on this.

**Comment by barbeau** [comment]
If the feed is a duplicate, we don't need to run it through rule validation at all.
